/******************************************************************************
 *
 * Copyright (c) 1995-1999 Palm Computing, Inc. or its subsidiaries.
 * All rights reserved.
 *
 * File: Category.h
 *
 * Description:
 *            Short description of what the file implements, who uses it 
 *            and how it fits into the larger world.
 *
 * History:
 *              March 7, 1995   Created by Art Lamb
 *      7/14/99   bob - fix up const junk
 *                8/12/99       gap - add new constants categoryHideEditCategory
 *                                    & categoryDefaultEditCategoryString.
 *
 * (c) HSPascal April-2001, Pascal syntax for HSPascal http://HSPascal.Fihl.net
 *
 *****************************************************************************/

Unit Category;

interface

Uses {$ifdef PalmVer35} Traps30, {$endif}
     Control, DataMgr, Form, List;

// Note: although these constants are in the range of system resource IDs, the are actually
// constants passed to CategoryCreateList, CategorySelect, and CategoryFreeList which will
// produce the desired action.  The reason the constants are in this range is to keep them
// out of the numeric range that developers can use for resource IDs in the attempt to avoid
// conflicts.

Const
  categoryHideEditCategory             =10000;
  categoryDefaultEditCategoryString    =10001;

Type
  AppInfoPtr = ^AppInfoType;
  AppInfoType = Record
    renamedCategories: UInt16;
    categoryLabels: Array [0..dmRecNumCategories-1] Of String[dmCategoryLength-1];
    categoryUniqIDs: Array [0..dmRecNumCategories-1] of UInt8;
    lastUniqID: UInt8; // Uniq IDs generated by the device are between
                       // 0 - 127.  Those from the PC are 128 - 255.
    padding: UInt8;
  End;

Procedure CategoryCreateListV10 (db: DmOpenRef; var lst: ListType;
   currentCategory: UInt16; showAll: Boolean);
                     SYS_TRAP(sysTrapCategoryCreateListV10);

Procedure CategoryCreateList (db: DmOpenRef; var listP: ListType;
   currentCategory: UInt16; showAll: Boolean;
   showUneditables: Boolean; numUneditableCategories: UInt8;
   editingStrID: UInt32; resizeList: Boolean);
                     SYS_TRAP(sysTrapCategoryCreateList);


Procedure CategoryFreeListV10 (db: DmOpenRef; var lst: ListType);
                     SYS_TRAP(sysTrapCategoryFreeListV10);

Procedure CategoryFreeList (db: DmOpenRef; var listP: ListType;
   showAll: Boolean; editingStrID: UInt32);
                     SYS_TRAP(sysTrapCategoryFreeList);

Function CategoryFind (db: DmOpenRef; name: String): UInt16;
                     SYS_TRAP(sysTrapCategoryFind);

Procedure CategoryGetName (db: DmOpenRef; index: UInt16; name: String);
                     SYS_TRAP(sysTrapCategoryGetName);

Function CategoryEditV10 (db: DmOpenRef; var category: UInt16): Boolean;
                     SYS_TRAP(sysTrapCategoryEditV10);

Function CategoryEditV20 (db: DmOpenRef; var category: UInt16;
   titleStrID: UInt32): Boolean;
                     SYS_TRAP(sysTrapCategoryEditV20);

{$ifdef PalmVer35}
Function CategoryEdit (db: DmOpenRef; var category: UInt16;
   titleStrID: UInt32; numUneditableCategories: UInt8): Boolean;
                     SYS_TRAP(sysTrapCategoryEdit);
{$endif}

Function CategorySelectV10 (db: DmOpenRef; var frm: FormType;
   ctlID, lstID: UInt16; title: Boolean; var category: UInt16;
   categoryName: String): Boolean;
                     SYS_TRAP(sysTrapCategorySelectV10);

Function CategorySelect (db: DmOpenRef; var frm: FormType;
   ctlID, lstID: UInt16; title: Boolean; var category: UInt16;
   categoryName: String; numUneditableCategories: UInt8;
   editingStrID: UInt32): Boolean;
                     SYS_TRAP(sysTrapCategorySelect);

Function CategoryGetNext (db: DmOpenRef; index: UInt16): UInt16;
                     SYS_TRAP(sysTrapCategoryGetNext);

Procedure CategorySetTriggerLabel (var ctl: ControlType; name: String);
                     SYS_TRAP(sysTrapCategorySetTriggerLabel);

Procedure CategoryTruncateName (name: String; maxWidth: UInt16);
                     SYS_TRAP(sysTrapCategoryTruncateName);

Procedure CategoryInitialize (appInfoP: AppInfoPtr; localizedAppInfoStrID: UInt16);
                     SYS_TRAP(sysTrapCategoryInitialize);


Procedure CategorySetName (db: DmOpenRef; index: UInt16; name: String);
                     SYS_TRAP(sysTrapCategorySetName);

implementation

end.

