// Original file name: Controls.h
// Generated by Arbor piBuilder @ 10.04.2001 12:29:12

#define Form1   0x800
#define Label2  0x801
#define Field3  0x802
#define CheckBox5 0x803
#define PopupTrigger6 0x804
#define List7   0x805
#define btPushme 0x806
#define ListPrime 0x807
#define LabelProgress 0x808




